version: '3.8'

services:
  humanize-text:
    build:
      context: dawoodalam057/humanize-text
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env-file:
      - .env
    system:
      restart: always
    